### PR TITLE
Add links to expression references under "Idiomatic Rust", too

### PR DESCRIPTION
**Pull request by kud1ing**
People might stumbled on "expressions" here first, that's why i've duplicated the links from the table under `Miscellaneous`.

### CODE REVIEW

**Comment by kud1ing** [comment]
Alternatively we could create an "Expressions" section and point there, instead of duplicating the external references.

**Comment by ralfbiedert** [comment]
"Expressions" is hard since the term is used a few times in the whole sheet. I probably wouldn't want to randomly repeat links, but if each entry in "Idioms" had one link to a further reading that might help people.

We can keep one for Expressions (which one?), and then add more links to the others. I'm also happy to add links to non-official sites if they do a great job explaining the concept.

**Comment by kud1ing** [comment]
I think many people are browsing the cheat sheet (wasn't that also a result in the survey?). So it's likely that they jump non-linearly into any section where they are met with expressions (pun intended) they are not familiar with yet.

I think having short sections like "expressions" and "iterators/iteration" etc. with the links to the book etc. are not a such a bad idea and throughout the cheat sheet the links could refer to those sections only. What do you think?

**Comment by ralfbiedert** [comment]
> I think many people are browsing the cheat sheet (wasn't that also a result in the survey?). So it's likely that they jump non-linearly into any section where they are met with expressions (pun intended) they are not familiar with yet.

Yes! Most people seem to come to browse and I'd also assume they jump a lot. My comment was more about that I'd like to avoid redundant information, but I agree that the current place for "expressions" might not be the best one.

> I think having short sections like "expressions" and "iterators/iteration" etc. with the links to the book etc. are not a such a bad idea and throughout the cheat sheet the links could refer to those sections only. What do you think?

Could you maybe (in a super quick way) sketch what you envision when you say "short sections like expressions and iterators" and how you would link from there?

**Comment by kud1ing** [comment]
Roughly:
```
# Expressions

Expressions are ...
(Link to Rust reference about expressions)
(Link to Rust book about expressions)
etc.

# Iterators

Iterators are ...
(Link to Rust reference about iterators)
(Link to Rust book about iterators)
etc.

# Idiomatic Rust

Think in Expressions (link to "Expressions" section above)
...

# Miscellaneous

x; | Statement REF terminator, c. expressions (link to "Expressions" section above)
```

**Comment by kud1ing** [comment]
I must admit i am not sure whether every such (mini) section would fit in the cheat sheet itself or would have to live somewhere extra.

**Comment by ralfbiedert** [comment]
Thanks for sketching! Random comments from the top of my head:

- Maybe I misread it, but this seems to want to go before the [misc section](https://cheats.rs/#miscellaneous). I wouldn't put it there, but rather under Guides.
- Reminds me vaguely of [this](https://github.com/JasonShin/fp-core.rs)
- Almost have the feeling this is a "Fundamental Concepts" section?
- Alternatively (in lack of better name) a library "Big Five" section, writing a few words about some of Rust's std's most fundamenal and/or unique concepts (Iterators, Expressions, Traits, ...). 
- Regardless what, I'd like to avoid lengthily explaning basic concepts and "average" C / Java / Python engineer would already know or might easily infer. but instead only list very condensed essentials.

**Comment by kud1ing** [comment]
`fp-core` looks interesting, but i think it should be smaller than that - more like a glossary.

I have no strong opinion about where to put it. I could fancy a section about iteration/iterators prominently being under "Language Constructs". The others could be more hidden.

**Comment by kud1ing** [comment]
Yeah, i think i like the glossary format. E.g. https://en.wikipedia.org/wiki/Glossary_of_computer_graphics

**Comment by kud1ing** [comment]
Closing this PR since i'd prefer the sections ansatz we've discussed.

**Pull request closed without merging**
