### PR TITLE
Const variables are not mutable

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by ralfbiedert** [comment]
Thanks. How would you warn about / express that this is valid:

```rust
struct S(i32);

fn main() {
    const C: S = S(0);
    C.0 = 123;
}
```

When I was learning Rust I found it surprising that the inlined value could be changed.

**Comment by gnzlbg** [comment]
The value is not changed: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0d031013321c315cc5f0d27741c1b485

**Comment by killercup** [comment]
I think @ralfbiedert meant something like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=66e9ddef0e376a2bdb190f999e61b20e). This is quite a weird edge-case. I haven't seen a lot of local constants in Rust code, too.

**Comment by ralfbiedert** [comment]
@killercup yes both that and the fact that it looks like you can set `C.0`, which implicitly creates an inlined value that accepts that change.

**Comment by gnzlbg** [comment]
@killercup 

> I think @ralfbiedert meant something like this.

That example isn't modifying a constant, it is copying the constant into a mutable local, and mutating the local. The value of the constant remains the same. That isn't that much different from:

```rust
let a = 2; // immutable
let mut b = a; // mutable
b = 3; // modified mutable b
```

I've never seen an user claim that the `b = 3` assignment modifies `a`.

> @killercup yes both that and the fact that it looks like you can set C.0, 

You can't set C.0. If you open the playground link I showed above, `C.0 = 123; dbg!(C)` prints `C.0 == 0`, the `C.0 = 123;` does nothing.

**Comment by gnzlbg** [comment]
@ralfbiedert when one uses a constant like `const C`, a mutable temporary is created, and one operates on that. So `C.0 = 123;` basically expands to this:

```rust
{ 
    let mut tmp = C.0;
    tmp = 123;
}
```

That does not mean that the constant is modified, it isn't. What's modified is the mutable temporary that gets constructed when you read the value from the constant.

**Comment by killercup** [comment]
@gnzlbg yes, if it wasn't clear I actually agree with you and this change. Rust's constants are *not* like "bindings" or "memory location". (This makes it confusing unless used like in my example where you explicitly create a binding first with the _value_ of the constant, after which you are dealing with the binding and not doing stuff to the constant.)

**Comment by ralfbiedert** [comment]
@gnzlbg, maybe I'm missing something, but isn't that exactly what the current site is saying:

>  | `const X: T = T();`  | Define inlineable constant. **Inlined values** are mutable!!! |

However the PR is about removing that part, saying "const variables are not mutable". In my understanding, saying "inlined values" should refer to the temporary, not the constant.

> You can't set C.0. If you open the playground link I showed above, C.0 = 123; dbg!(C) prints C.0 == 0, the C.0 = 123; does nothing.

Again, I was not suggesting that this is possible. However, what was somewhat confusing is that `C.0 = 123` **looks** as if you could do that. 

If I'm new to Rust (or a new language), couldn't it be reasonable to assume that an `C.0 = 123` would rather fail? According to your example:

```rust
let a = S(2); // immutable
a.0 = 123; // this would be mildly surpising 
```

With all of that in mind, could you just quickly recap why it would be wrong to say that "**inlined values** are mutable", @gnzlbg?

**Comment by gnzlbg** [comment]
@ralfbiedert 

> With all of that in mind, could you just quickly recap why it would be wrong to say that "inlined values are mutable

I think that it is suboptimal to explain things this way. A `const` is just an immutable constant without any storage, e.g., like just the literal `3`. When these are used, they get put into a temporary storage that can be mutated. IIRC, there is nothing more to it.

I think that explaining that is simpler and more useful than introducing the concept of "inlined values", which isn't really a concept that Rust has. 

Once one understands that, one doesn't only understand what `C.0 = 123` actually does, but also, for example, what the statement `*(&mut 3) = 42;` does. You are able to transfer this knowledge to any situation where you might need it and it will work without surprises.

I agree with you that such code looks like the constant `C` or the literal `3` are being modified. This is surprising for both beginners and experienced Rust programmers. The best way to improve that is to teach something that removes the surprise.

**Comment by gnzlbg** [comment]
FWIW, see https://github.com/rust-lang/rust/issues/55721 - the unused values lint should complain about unused temporaries like these, but it currently does not do that yet.

**Comment by ralfbiedert** [comment]
@gnzlbg thanks, yes, I agree your two-stage explanation is better. How about this then instead of the current text:

> Defines constant. Inlined as temporary copy when used.

**Comment by gnzlbg** [comment]
Better. What about:

> Defines constant. Copied into a temporary when used 

? 

I'm not 100% that these are always copied into a temporary when used, but that would be close enough for me.

**Pull request merged**
