### PR TITLE
Small grammar fix: "why" -> "which" in Weaknesses

### PR DESCRIPTION
**Pull request by benediktwerner**
English is not my native language but I'm pretty sure the sentence is not correct as it is? At least it sounds strange to me.

### CODE REVIEW

**Comment by ralfbiedert** [comment]
Thanks for the PR. Not a native speaker, and not sure either. Will keep the PR open a bit and see if someone can chime in.

**Comment by gnuyent** [comment]
What do you think about entirely removing the second part?

> careless (use of unsafe in) libraries can break safety guarantees ~for why Rust was picked in the first place~.

I think it makes it more concise since we talk about memory safety in the strengths section.

**Comment by ralfbiedert** [comment]
> I think it makes it more concise since we talk about memory safety in the strengths section.

Yes, I like it! Would it be fair to add a "secretly", which is what I think the real problem is:

- careless (use of unsafe in) libraries can **secretly** break safety guarantees

**Comment by benediktwerner** [comment]
Sounds good. I adjusted the PR.

**Comment by gnuyent** [comment]
> Yes, I like it! Would it be fair to add a "secretly", which is what I think the real problem is:
> 
>     * careless (use of unsafe in) libraries can **secretly** break safety guarantees

This sounds great!

**Comment by ralfbiedert** [comment]
Thanks!

**Pull request merged**
