### PR TITLE
union is still disjoint relation

### PR DESCRIPTION
**Pull request by jinmingjian**
why we use "and" rather than "or" here?

### CODE REVIEW

**Comment by ralfbiedert** [comment]
With one word (`and`) I wanted to express that they can be used for unsafe type conversion, you can write a `u32` and later treat it as if you had written 4 `u8`: In contrast to `enum`, the language doesn't enforce that you either use one alternative or the other. 

Any thoughts how that should be expressed? Call enum `xor` and union `or`? Make both `or` and ignore that fact?

**Comment by jinmingjian** [comment]
Got it. You want to emphasize the fact the union (in C) is unsafe. (In some extent, it could use enum + union + struct + proxy function in C to mock great Rust enum...)

But, "and" is still **not accurate** obviously. For,
1. the "share-memory" effect of members of union is not strictly "and"
2. the anti-symmetry between "or" and "and" makes confusions especially for the obsessive (after all, tagged union is seen as a upgrade of union) 

how about following change:
* and -> or (but unsafely overlapped with)
or
* and -> or (but unsafely shared memory space with)

**Comment by ralfbiedert** [comment]
> the "share-memory" effect of members of union is not strictly "and"

I'd argue it is also not strictly "or" (in the `enum` sense of exclusive "or"): 

While an enum forces me to treat a some memory as either A _or_ B for a given lifetime, unions (de-facto) allow me treat the same memory as A _and_ B (write an `a`, call method on `b`, read `a` again).  The result might not be defined, but the language won't stop me. 

> how about following change:

I'm happy to change it, but there is only space for ~10 characters, otherwise the box overflows.

**Comment by ralfbiedert** [comment]
Update, I made some changes to these lines (tentatively published, subject to further discussion), can you have a look and comment?

**Comment by jinmingjian** [comment]
Great! It is enough to deliver our intention now.

**Pull request merged**
