### PR TITLE
add example for string concatenation to demonstrate what to do when the LHS implements fmt:: or io::Write

### PR DESCRIPTION
**Pull request by cosmobobak**

### CODE REVIEW

**Comment by cosmobobak** [comment]
image of my proposed addition:
image

**Comment by ralfbiedert** [comment]
Thanks. We can add write here, but I'd explain something like "Append y to x ..."? I might be off here but semantically concatenate to me implies c=a+b, while append is a+=b.

**Comment by cosmobobak** [comment]
that's fair! the existing example is correct if both strings need to live beyond their concatenation (assuming format!("{x}{y}") correctly creates a String::with_capacity(x.len() + y.len()), that is) - I just saw the footnote and wanted to provide an example. 
Now that I re-read this, i should probably also add the '21 tag because my example relies on the new string interpolation syntax

**Comment by ralfbiedert** [comment]
Thanks!

**Pull request merged**
