### PR TITLE
Add link to latest generated PDF

### PR DESCRIPTION
**Pull request by patriksvensson**
I realized a couple of days ago that you now generate a PDF document of the site, which I personally find super useful. It's not very discoverable though, so I thought I would submit this PR that adds a link to the README.

Not sure if this is something that you want, so feel free to close this PR if you don't feel like merging it.

### CODE REVIEW

**Comment by ralfbiedert** [comment]
I have mixed feelings about the PDF download in general. 

There is no good way to automatically create it when the site updates, so it's always outdated. On the other hand, some platforms like iOS can't generate it themselves, so it needs to be there. 

Which is why on the main site the PDF option is hidden deep below, and I'd rather have people produce it themselves if they can. 

With that said, I agree it could be linked from the main README, but it probably needs a sentence saying it's only plan b.

**Comment by ralfbiedert** [comment]
Update: I went all-in ...  let me know if you think that's too much on the nose :)

**Comment by patriksvensson** [comment]
Looks awesome!

This is a bit embarassing to admit, but I didn’t realize there was a way of generating a PDF directly on the site! 😅

**Comment by patriksvensson** [comment]
But, how about having a GitHub action that generates the PDF and attaches it to the release when you create a new release? Is the PDF generation possible to do from within a Docker container somehow?

**Comment by ralfbiedert** [comment]
Hah, never considered that! I created a ticket.

**Pull request merged**
