### PR TITLE
Using Iterators: add a mention to '.inspect()'

### PR DESCRIPTION
**Pull request by Hyask**
This method deserves more visibility imho.

Thanks a lot for this awesome page, really helpful for a beginner!

### CODE REVIEW

**Comment by ralfbiedert** [comment]
Thanks for the PR. 

I'm not opposed documenting some useful iterator methods, but I think that tab is the wrong place, as it is about "getting iterators to work", contrasted by its sibling tab "getting an iterator implementation to work".

I've renamed the tab to reflect that.

Adding more methods, I'd probably [follow this example](https://upsuper.github.io/rust-cheatsheet/), although it would need some experimentation what looks best, and where to draw the line between being a cheat sheet, and just listing everything that's in the standard docs.

**Comment by Hyask** [comment]
Indeed, a listing of the standard documentation is not what I had in mind either, but I thought that this method completely fall in the second and third use cases of the README (discover, and learn about Rust), because it may instantly help any one that starts playing with iterators, or anyone that wants to hack in an existing complex chain of iterator method.

If you don't see it in this tab, do you have a suggestion? I personally looked for it here before not finding it and asking my colleague instead, because that's the only section that really is about iterators. Maybe in the `Coding guides`>`Idiomatic Rust`?

**Comment by ralfbiedert** [comment]
> I thought that this method completely fall in the second and third use cases of the README (discover, and learn about Rust), 

Absolutely!

> If you don't see it in this tab, do you have a suggestion? 

Unfortunately I don't have a good answer when it comes to adding a new class of information that doesn't exist yet. I usually have to try a few things myself and before I'm happy. 

Right now I'd probably start by investigating a "Type Carousel" (name TBD) residing in "Standard Library", probably created below "One Liners" that is heavily inspired by (or even shamelessly stolen from) the Type-Based Rust Cheat Sheet linked above, but adapted to fit our page style. 

What I'd like about that approach would be that it has reasonable complexity, i.e., it doesn't just list a few random methods but gives a nice getting-started overview. On the other hand, the map like presentation of the other page is pretty damn good, and maybe adapting it for our page might degrade its appeal. 

There surely are other ways of doing that as well, and I'm open to discuss. In the end the my main factor is whether the resulting cheat sheet feels "well rounded".

**Comment by Hyask** [comment]
Okay, now I see clearly what you have in mind. Indeed, this kind of section with a lot of tips-and-tricks for various standard types would be great. Unfortunately, when it comes to nice and fancy web-design, my skills tend to dig below ground-level, so I won't be of much help experimenting in this direction.

Feel free to do whatever you want with this PR, either closing it unmerged, or merging it temporarily before you come with anything better. :-)

**Comment by ralfbiedert** [comment]
As discussed, closing in favor of more general section later.

**Pull request closed without merging**
