### PR TITLE
Add more cargo-tools

### PR DESCRIPTION
**Pull request by killercup**

### CODE REVIEW

**Comment by killercup** [comment]
Hope the formatting is fine

**Comment by ralfbiedert** [comment]
Hi, thanks! Does `flamegraph` work on Windows?

**Comment by killercup** [comment]
Don't think so, it uses dtrace or perf as backends

**Comment by ralfbiedert** [comment]
Ok. I'll merge then but remove flamegraph, since I'd prefer to only have tools that "just work". Agree?

**Comment by killercup** [comment]
Or add a note saying "only Linux and macOS"? It's a super useful tool :)

**Pull request merged**
